### ISSUE TITLE
点击组件的时候，页面会抖动

### ISSUE THREAD

**Issue by dsky1990** [thx/magix-project#1]
点击组件的时候，页面会抖动

**Comment by xinglie** [comment]
对，这个是一个效果，代码这里：https://github.com/thx/magix-project/blob/gh-pages/tmpl/app/views/coms/index.js#L36

magix-project并不是一个完整工程的示例，里面包含了很多常用代码及算法，每个页面都是很不专业的展示，回头我会好好花时间，把组件及项目开发中的经验给整进来，目前只是相当凌乱的整了下

**Comment by dsky1990** [comment]
感觉抖动这个效果是不是有点奇怪，好的，学习学习

**Comment by xinglie** [comment]
好的，我回头把它去掉先

**Comment by xinglie** [comment]
已切新版
